spring:
  application:
    name: demo
  jpa:
    show_sql: true

  logging:
    level:
      org.flywaydb: DEBUG

  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: appuser
    password: password123
